version: "2.25.0"

services: 
  frontendimg:
    build: /root/DevPractice/frontend
    container_name: frontend
    ports: 
      - 80:80
    network_mode: bridge

  backendimg:  
    build: /root/DevPractice/backend
    container_name: backend
    ports: 
      - 8080:8080
    network_mode: bridge
    depends_on:
      - "frontendimg"
