version: '3'
services:
  backendimg:
    build: .
    container_name: backend_container  
    ports:
      - "8080:8080"

  frontendimg:
    build: /root/DevPractice/Fronend/  # Absolute path to the Dockerfile for frontend
    container_name: frontend_container  
    ports:
      - "80:80"
    depends_on:
      - backendimg
